### ISSUE TITLE
System.OverflowException: Arithmetic operation resulted in an overflow in MonitorFactory.Create and SCardContext.GetReaders

### ISSUE THREAD

**Issue by BtbN** [danm-de/pcsc-sharp#77]
```
btbn@btbn ~/publish_linux_x64 $ ./FlagCarrierMini -v -k xxx

Unhandled Exception: System.OverflowException: Arithmetic operation resulted in an overflow.
   at PCSC.Interop.Unix.PCSCliteAPI.EstablishContext(SCardScope dwScope, IntPtr pvReserved1, IntPtr pvReserved2, IntPtr& phContext)
   at PCSC.SCardContext.Establish(SCardScope scope)
   at PCSC.ContextFactory.Establish(SCardScope scope)
   at PCSC.Monitoring.SCardMonitor..ctor(IContextFactory contextFactory, SCardScope scope)
   at PCSC.Monitoring.MonitorFactory.Create(SCardScope scope)
   at FlagCarrierBase.NfcHandler.StartMonitoring(String[] readerNames) in C:\Cygwin\home\Timo\Projekte\FlagCarrierWin\FlagCarrierBase\Handlers\NfcHandler.cs:line 80
   at FlagCarrierMini.FlagCarrierMini.Start() in C:\Cygwin\home\Timo\Projekte\FlagCarrierWin\FlagCarrierMini\FlagCarrierMini.cs:line 50
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at FlagCarrierMini.Program.Main(String[] args) in C:\Cygwin\home\Timo\Projekte\FlagCarrierWin\FlagCarrierMini\Program.cs:line 33
[1]    31603 abort (core dumped)  ./FlagCarrierMini -v -k xxx
btbn@btbn ~/publish_linux_x64 $ sudo systemctl start pcscd.socket
btbn@btbn ~/publish_linux_x64 $ ./FlagCarrierMini -v -k xxx

Unhandled Exception: System.OverflowException: Arithmetic operation resulted in an overflow.
   at PCSC.Interop.Unix.PCSCliteAPI.ListReaders(IntPtr hContext, String[] groups, String[]& readers)
   at PCSC.SCardContext.GetReaders(String[] groups)
   at FlagCarrierBase.NfcHandler.GetReaderNames() in C:\Cygwin\home\Timo\Projekte\FlagCarrierWin\FlagCarrierBase\Handlers\NfcHandler.cs:line 40
   at FlagCarrierBase.NfcHandler.StartMonitoring(String[] readerNames) in C:\Cygwin\home\Timo\Projekte\FlagCarrierWin\FlagCarrierBase\Handlers\NfcHandler.cs:line 89
   at FlagCarrierMini.FlagCarrierMini.Start() in C:\Cygwin\home\Timo\Projekte\FlagCarrierWin\FlagCarrierMini\FlagCarrierMini.cs:line 50
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at FlagCarrierMini.Program.Main(String[] args) in C:\Cygwin\home\Timo\Projekte\FlagCarrierWin\FlagCarrierMini\Program.cs:line 33
[1]    16776 abort (core dumped)  ./FlagCarrierMini -v -k xxx
```

The first error probably happened because pcscd wasn't running, and the second one because the system does not actually have any readers connected.

It would be nice if those situations would be handled more gracefully.

**Comment by BtbN** [comment]
I suspect SCardHelper.ToSCardError is where the error is coming from. Calling both those functions from C is returning an error code that should normally be recngonized fine(i.e. it's in the enum), and specially in EstablishContext there really isn't much else that can go wrong.
